const flightsConstants = {
    SAVE_RESERVATION: 'SAVE_RESERVATION',
    DELETE_RESERVATION: 'DELETE_RESERVATION',

    FETCH_ORIGIN_BEGIN: 'FETCH_ORIGIN_BEGIN',
    FETCH_ORIGIN_SUCCESS: 'FETCH_ORIGIN_SUCCESS',
    FETCH_ORIGIN_ERROR: 'FETCH_ORIGIN_ERROR',

    FETCH_DESTINY_BEGIN: 'FETCH_DESTINY_BEGIN',
    FETCH_DESTINY_SUCCESS: 'FETCH_DESTINY_SUCCESS',
    FETCH_DESTINY_ERROR: 'FETCH_DESTINY_ERROR',

    FETCH_TIME_BEGIN: 'FETCH_TIME_BEGIN',
    FETCH_TIME_SUCCESS: 'FETCH_TIME_SUCCESS',
    FETCH_TIME_ERROR: 'FETCH_TIME_ERROR',
};

export default flightsConstants;
