export const flightsConstants = {
    FETCH_FLIGHT_BEGIN: 'FETCH_FLIGHT_BEGIN',
    FETCH_FLIGHT_SUCCESS: 'FETCH_FLIGHT_SUCCESS',
    FETCH_FLIGHT_ERROR: 'FETCH_FLIGHT_ERROR',
};

export const reservationConstants = {
    FETCH_RESERVATION_BEGIN: 'FETCH_RESERVATION_BEGIN',
    FETCH_RESERVATION_SUCCESS: 'FETCH_RESERVATION_SUCCESS',
    FETCH_RESERVATION_ERROR: 'FETCH_RESERVATION_ERROR',
};
